# Uncomment the next line to define a global platform for your project

    #source 'https://github.com/artsy/Specs.git'
    source 'https://github.com/CocoaPods/Specs.git'
    source 'https://github.com/XiaoFuGenius/xiaofu-specs.git'

  platform :ios, '8.0'
  target 'Demo-OC' do

    # Pods for Demo-OC
    # pod install --verbose --no-repo-update
    # pod update --verbose --no-repo-update

#    开发阶段，支持模拟器调试UI
    #pod 'CameraDrive-release'
    #pod 'XiaoFuTech-release'

#    发布阶段，不支持模拟器调试UI
    pod 'CameraDrive-develop'
    pod 'XiaoFuTech-develop'

end
